### ISSUE TITLE
Documentation: How to Install.

### ISSUE THREAD

**Issue by JamieRCHI** [NotoriousPyro/WasteManagement#1]
There are a lot of people new to mods and don't know how to install them. 
Could you add instructions to the readme files of both your mods?
With the location to put them?
Also, it wouldn't hurt to mention that a new game may be required for your mods to work.
(Although your new research may not have shown up because I already researched everything in the current game save I am playing.)
And maybe show a picture of the menu in COI where to enable mods. 

I already have been using Captain of Cheats mod for quite awhile so I was able to get started.
I did verify that the new research does show up in the Research Dialog on a new game with the Captain of Cheats mod installed.
Haven't tested anything other than that because I already started a new map. 

Finally, all of the other mods I have seen, place the mod files in a folder with the same name of the mod DLL. 
Then the entire folder containing the mod is placed in the Documents\Captain of Industry\Mods folder.
I noticed that the official modding page on Github for COI tells us to do that. 
(They didn't say to put the pdb file in there for some reason.)

Thanks for these mods. I really like the idea of the unpowered balancers. They are really needed when placing with the steam power builds to increase their reliability and restartability if I run out of power because I wasn't paying attention to the coal inputs.

**Comment by NotoriousPyro** [comment]
You are right and it was something I wanted to improve but haven't yet got around to, after all the code is the real "beans" :).

There is no way to "enable" mods other than put them in the right folder and start a new game. Unfortunately, the mods are save-bound and this is out of our control as modders. Hopefully CoI will some day support hot plugging mods into already started saves.

The PDB is purely for your own use of debugging in case of crashing if needed. You do not need to use it.

**Comment by NotoriousPyro** [comment]
Delivered in [@v1.0](https://github.com/NotoriousPyro/WasteManagement/releases/tag/v1.0.1)
